config/routes.rb
Rails.application.routes.draw do

	resources :happenings

	resources :study_reservations
	
	get '/contracts/success'
	get '/contracts/failure'
	get '/amenities', to: 'static#amenities', as: :amenities
	get '/contracts_pricing', to: 'static#contracts_pricing', as: :pricing
	get '/galleries', to: 'static#galleries', as: :gallery
	get '/apartments', to: 'static#apartments', as: :apartments
	get '/tenant', to: 'static#tenant', as: :tenant
	get 'maintenances/created', to: 'maintenances#created'
	get '/buildings/:building_id/apartments/:semester_id', to: 'ajax#beds'
	get '/renew', to: 'contracts#renew'
	get '/userPayment', to: 'contracts#userPayment'
	get '/makePayment', to: 'static#makePayment'
	devise_for :admins
	root 'landing#landing'
	get '/contact', to: 'static#contact_manager', as: :contact_manager
	post '/contact', to: 'static#manager_email', as: :contact_email
	get '/choose/:semester_id/:building_id', to: 'static#choose'
	get '/choose/:semester_id', to: 'static#choose', as: :choose_apartment
	get '/complex', to: 'static#complex', as: :complex

	get '/success', to: 'contracts#success', as: :success

	post '/invoice', to: 'contracts#discounts', as: :discounts
	get '/invoice', to: 'contracts#discounts'

	get '/contracts/new/:building_id/:semester_id', to: 'contracts#new', as: :new_contract
	post '/contracts/new/:building_id/:semester_id', to: 'contracts#new'
	get '/buildings/:id/availability/:semester_id', to: 'availability#available'

	scope :admin do
		resources :amenities
		resources :galleries
		resources :buildings
		resources :semesters
		resources :contract_texts
		resources :maintenances
		resources :study_rooms
		resources :apartments

		
		get '/contracts', to: 'contracts#index', as: :contracts
		post '/contracts', to: 'contracts#create'
		get '/contracts/:id', to: 'contracts#show', as: :contract
		put '/contracts/:id', to: 'contracts#update'
		get '/contracts/:id/edit', to: 'contracts#edit', as: :edit_contract
		delete '/contracts/:id', to: 'contracts#destroy', as: :destroy_contract

		get '/', to: 'static#dashboard', as: :dashboard
		get '/marketing-text', to: 'static#marketing_text', as: :edit_text
		post '/marketing-text', to: 'static#edit_text', as: :update_text
	end

end

app/models/happening.rb
# == Schema Information
#
# Table name: happenings
#
#  id          :integer          not null, primary key
#  heading     :string(255)
#  description :text
#  date        :date
#  created_at  :datetime
#  updated_at  :datetime
#

class Happening < ActiveRecord::Base
end

app/controllers/happenings_controller.rb
class HappeningsController < ApplicationController
  before_action :authenticate_admin!, except: [:show, :index]
  before_action :set_happening, only: [:show, :edit, :update, :destroy]

  # GET /happenings
  # GET /happenings.json
  def index
    @happenings = Happening.all
  end

  # GET /happenings/1
  # GET /happenings/1.json
  def show
  end

  # GET /happenings/new
  def new
    @happening = Happening.new
  end

  # GET /happenings/1/edit
  def edit
  end

  # POST /happenings
  # POST /happenings.json
  def create
    @happening = Happening.new(happening_params)

    respond_to do |format|
      if @happening.save
        format.html { redirect_to @happening, notice: 'Happening was successfully created.' }
        format.json { render :show, status: :created, location: @happening }
      else
        format.html { render :new }
        format.json { render json: @happening.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /happenings/1
  # PATCH/PUT /happenings/1.json
  def update
    respond_to do |format|
      if @happening.update(happening_params)
        format.html { redirect_to @happening, notice: 'Happening was successfully updated.' }
        format.json { render :show, status: :ok, location: @happening }
      else
        format.html { render :edit }
        format.json { render json: @happening.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /happenings/1
  # DELETE /happenings/1.json
  def destroy
    @happening.destroy
    respond_to do |format|
      format.html { redirect_to happenings_url, notice: 'Happening was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_happening
      @happening = Happening.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def happening_params
      params.require(:happening).permit(:heading, :description, :date)
    end
end

app/helpers/happenings_helper.rb
module HappeningsHelper
end

app/views/happenings/_form.html.haml
= form_for @happening do |f|
  - if @happening.errors.any?
    #error_explanation
      %h2= "#{pluralize(@happening.errors.count, "error")} prohibited this happening from being saved:"
      %ul
        - @happening.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :heading
    = f.text_field :heading
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :date
    = f.date_select :date
  .actions
    = f.submit 'Save'

app/views/happenings/edit.html.haml
%h1 Editing happening

= render 'form'

= link_to 'Show', @happening
\|
= link_to 'Back', happenings_path

app/views/happenings/index.html.haml
%h1 Listing happenings

%table
  %tr
    %th Heading
    %th Description
    %th Date
    %th
    %th
    %th

  - @happenings.each do |happening|
    %tr
      %td= happening.heading
      %td= happening.description
      %td= happening.date
      %td= link_to 'Show', happening
      - if admin_signed_in?
        %td= link_to 'Edit', edit_happening_path(happening)
        %td= link_to 'Destroy', happening, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br
- if admin_signed_in?
  = link_to 'New Happening', new_happening_path

app/views/happenings/new.html.haml
%h1 New happening

= render 'form'

= link_to 'Back', happenings_path

app/views/happenings/show.html.haml
%p#notice= notice

%p
  %b Heading:
  = @happening.heading
%p
  %b Description:
  = @happening.description
%p
  %b Date:
  = @happening.date
- if admin_signed_in?
  = link_to 'Edit', edit_happening_path(@happening)
  \|
  = link_to 'Back', happenings_path