config/routes.rb
Rails.application.routes.draw do

	resources :happenings

	resources :study_reservations
	
	get '/contracts/success'
	get '/contracts/failure'
	get '/amenities', to: 'static#amenities', as: :amenities
	get '/contracts_pricing', to: 'static#contracts_pricing', as: :pricing
	get '/galleries', to: 'static#galleries', as: :gallery
	get '/apartments', to: 'static#apartments', as: :apartments
	get '/tenant', to: 'static#tenant', as: :tenant
	get 'maintenances/created', to: 'maintenances#created'
	get '/buildings/:building_id/apartments/:semester_id', to: 'ajax#beds'
	get '/renew', to: 'contracts#renew'
	get '/userPayment', to: 'contracts#userPayment'
	get '/makePayment', to: 'static#makePayment'
	devise_for :admins
	root 'landing#landing'
	get '/contact', to: 'static#contact_manager', as: :contact_manager
	post '/contact', to: 'static#manager_email', as: :contact_email
	get '/choose/:semester_id/:building_id', to: 'static#choose'
	get '/choose/:semester_id', to: 'static#choose', as: :choose_apartment
	get '/complex', to: 'static#complex', as: :complex

	get '/success', to: 'contracts#success', as: :success

	post '/invoice', to: 'contracts#discounts', as: :discounts
	get '/invoice', to: 'contracts#discounts'

	get '/contracts/new/:building_id/:semester_id', to: 'contracts#new', as: :new_contract
	post '/contracts/new/:building_id/:semester_id', to: 'contracts#new'
	get '/buildings/:id/availability/:semester_id', to: 'availability#available'

	scope :admin do
		resources :amenities
		resources :galleries
		resources :buildings
		resources :semesters
		resources :contract_texts
		resources :maintenances
		resources :study_rooms
		resources :apartments

		
		get '/contracts', to: 'contracts#index', as: :contracts
		post '/contracts', to: 'contracts#create'
		get '/contracts/:id', to: 'contracts#show', as: :contract
		put '/contracts/:id', to: 'contracts#update'
		get '/contracts/:id/edit', to: 'contracts#edit', as: :edit_contract
		delete '/contracts/:id', to: 'contracts#destroy', as: :destroy_contract

		get '/', to: 'static#dashboard', as: :dashboard
		get '/marketing-text', to: 'static#marketing_text', as: :edit_text
		post '/marketing-text', to: 'static#edit_text', as: :update_text
	end

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
	before_action :availability
	def landing
	end

	private
	def availability
		@marketing_text = MarketingText.first
		@marketing_text = @marketing_text.text if @marketing_text
		@marketing_text ||= ""
		@semesters = Semester.where('start_date >= ?', Date.today - 30).order(:start_date).limit(6)
	end
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/views/landing/_availability_bar.html.haml
.availability-bar
	%h3.check-text
		Check Availability:
	%p.col-xs-12.col-sm-2.col-md-3
		= select_tag :semester, options_from_collection_for_select(@semesters, 'id', 'name'), class: ['form-control', 'col-md-2'], id: :'sem-select'
	.col-xs-3.col-sm-2.col-md-1.col-md-offset-1.col-lg-offset-1.gender-icon#womens
		= image_tag 'women_bg.png'
		%p Women
	.col-xs-3.col-sm-2.col-md-1.gender-icon#mens
		= image_tag 'men_bg.png'
		%p Men
	.text-center.btn-blocky#available-answer
		%p 

app/views/landing/landing.html.haml
/ Main jumbotron for a primary marketing message or call to action
.container-fluid
	.row.image
		= image_tag 'building_cropped.png'
		.marketing-bar
			= @marketing_text
	
	= render 'landing/availability_bar'

	.tiles
		#complex-tile.tile
			= link_to amenities_path, class: :"inner-tile" do
				.tile-overlay
					%h3 Complex
		#apartments-tile.tile
			= link_to apartments_path, class: :"inner-tile" do
				.tile-overlay
					%h3 Apartments
		#contracts-tile.tile
			= link_to pricing_path, class: :"inner-tile" do
				.tile-overlay
					%h3 Contracts
.container.visible-xs
	.marketing-bar
		%h2.text-center
			= @marketing_text
	/= render 'news'
	#social.row
		%h3.col-md-12.text-center Follow us on
		#social-icons.col-md-12
			.cntr.fit-width
				%a{:href => ""}
					= image_tag 'facebook.png'
				%a{:href => ""}
					= image_tag 'twitter.png'
	%hr/
	%footer
		.cntr.fit-width
			%a(href="mailto:managers@windsormanor.net?Subject=Windsor%20Manor%20" target="_top")
				<span class="contact_manager">Contact the manager</span>
		%p.text-center &copy; Windsor Manor 2014