config/routes.rb
Rails.application.routes.draw do

	resources :happenings

	resources :study_reservations
	
	get '/contracts/success'
	get '/contracts/failure'
	get '/amenities', to: 'static#amenities', as: :amenities
	get '/contracts_pricing', to: 'static#contracts_pricing', as: :pricing
	get '/galleries', to: 'static#galleries', as: :gallery
	get '/apartments', to: 'static#apartments', as: :apartments
	get '/tenant', to: 'static#tenant', as: :tenant
	get 'maintenances/created', to: 'maintenances#created'
	get '/buildings/:building_id/apartments/:semester_id', to: 'ajax#beds'
	get '/renew', to: 'contracts#renew'
	get '/userPayment', to: 'contracts#userPayment'
	get '/makePayment', to: 'static#makePayment'
	devise_for :admins
	root 'landing#landing'
	get '/contact', to: 'static#contact_manager', as: :contact_manager
	post '/contact', to: 'static#manager_email', as: :contact_email
	get '/choose/:semester_id/:building_id', to: 'static#choose'
	get '/choose/:semester_id', to: 'static#choose', as: :choose_apartment
	get '/complex', to: 'static#complex', as: :complex

	get '/success', to: 'contracts#success', as: :success

	post '/invoice', to: 'contracts#discounts', as: :discounts
	get '/invoice', to: 'contracts#discounts'

	get '/contracts/new/:building_id/:semester_id', to: 'contracts#new', as: :new_contract
	post '/contracts/new/:building_id/:semester_id', to: 'contracts#new'
	get '/buildings/:id/availability/:semester_id', to: 'availability#available'

	scope :admin do
		resources :amenities
		resources :galleries
		resources :buildings
		resources :semesters
		resources :contract_texts
		resources :maintenances
		resources :study_rooms
		resources :apartments

		
		get '/contracts', to: 'contracts#index', as: :contracts
		post '/contracts', to: 'contracts#create'
		get '/contracts/:id', to: 'contracts#show', as: :contract
		put '/contracts/:id', to: 'contracts#update'
		get '/contracts/:id/edit', to: 'contracts#edit', as: :edit_contract
		delete '/contracts/:id', to: 'contracts#destroy', as: :destroy_contract

		get '/', to: 'static#dashboard', as: :dashboard
		get '/marketing-text', to: 'static#marketing_text', as: :edit_text
		post '/marketing-text', to: 'static#edit_text', as: :update_text
	end

end

app/models/study_reservation.rb
# == Schema Information
#
# Table name: study_reservations
#
#  id            :integer          not null, primary key
#  study_room_id :integer
#  start         :time
#  stop          :time
#  date          :date
#  name          :string(255)
#  created_at    :datetime
#  updated_at    :datetime
#

class StudyReservation < ActiveRecord::Base
  belongs_to :study_room
end

app/controllers/study_reservations_controller.rb
class StudyReservationsController < ApplicationController
  before_action :authenticate_admin!, only: [:destroy]
  before_action :set_study_reservation, only: [:show, :edit, :update, :destroy]

  # GET /study_reservations
  # GET /study_reservations.json
  def index
    @study_reservations = StudyReservation.all
  end

  # GET /study_reservations/1
  # GET /study_reservations/1.json
  def show
  end


  # GET /study_reservations/new
  def new
    @study_reservation = StudyReservation.new
    @study_rooms = StudyRoom.all
  end

  # GET /study_reservations/1/edit
  def edit
	  @study_reservation = StudyReservation.find(params[:id])
	  @study_rooms = StudyRoom.all
  end

  # POST /study_reservations
  # POST /study_reservations.json
  def create
    @study_reservation = StudyReservation.new(study_reservation_params)

    respond_to do |format|
      if @study_reservation.save
        format.html { redirect_to @study_reservation, notice: 'Study reservation was successfully created.' }
        format.json { render :show, status: :created, location: @study_reservation }
      else
        format.html { render :new }
        format.json { render json: @study_reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /study_reservations/1
  # PATCH/PUT /study_reservations/1.json
  def update
    respond_to do |format|
      if @study_reservation.update(study_reservation_params)
        format.html { redirect_to @study_reservation, notice: 'Study reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @study_reservation }
      else
        format.html { render :edit }
        format.json { render json: @study_reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /study_reservations/1
  # DELETE /study_reservations/1.json
  def destroy
    @study_reservation.destroy
    respond_to do |format|
      format.html { redirect_to study_reservations_url, notice: 'Study reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_study_reservation
      @study_reservation = StudyReservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def study_reservation_params
      params.require(:study_reservation).permit(:study_room_id, :start, :stop, :date, :name)
    end
end

app/helpers/study_reservations_helper.rb
module StudyReservationsHelper
end

app/views/study_reservations/_form.html.haml
= form_for @study_reservation do |f|
  - if @study_reservation.errors.any?
    #error_explanation
      %h2= "#{pluralize(@study_reservation.errors.count, "error")} prohibited this study_reservation from being saved:"
      %ul
        - @study_reservation.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :study_room_id
    %select{name: :'study_reservation[study_room_id]', id: :study_reservation_study_room_id, :required => true}
      - @study_rooms.each do | study_room |
        %option{:value => study_room.id} #{study_room.rm_type + " " + String(study_room.rm_number)}
  .field
    = f.label :start
    = f.time_select :start
  .field
    = f.label :stop
    = f.time_select :stop
  .field
    = f.label :date
    = f.date_select :date
  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/study_reservations/edit.html.haml
%h1 Editing study_reservation

= render 'form'

= link_to 'Show', @study_reservation
\|
= link_to 'Back', study_reservations_path

app/views/study_reservations/index.html.haml
.container
  .row
    .col-md-12
      %h1 Study Room Reservations
    .col-md-12
      %table
        %tr
          %th Study room
          %th Start
          %th Stop
          %th Date
          %th Name
          %th
          %th
          %th
        - @study_reservations.each do |study_reservation|
          %tr
            %td= study_reservation.study_room.rm_type + " " + String(study_reservation.study_room.rm_number)
            %td= study_reservation.start
            %td= study_reservation.stop
            %td= study_reservation.date
            %td= study_reservation.name
            %td= link_to 'Show', study_reservation
            
            - if admin_signed_in?
              %td= link_to 'Destroy', study_reservation, :method => :delete, :data => { :confirm => 'Are you sure?' }
              %td= link_to 'Edit', edit_study_reservation_path(study_reservation)
  %br
  %br
  .row
    .col-md-12
      = link_to 'New Study reservation', new_study_reservation_path, class: ['btn', 'btn-primary']

app/views/study_reservations/new.html.haml
.container
  .row
    .col-md-12
      %h1 New study_reservation
  .row
    .col-md-12
      = render 'form'
  %br
  %br
  .row
    .col-md-12
      = link_to 'Back', study_reservations_path, class: ['btn', 'btn-default']

app/views/study_reservations/show.html.haml
%p#notice= notice

%p
  %b Study room:
  = @study_reservation.study_room.rm_type + " " + String(@study_reservation.study_room.rm_number)
%p
  %b Start:
  = @study_reservation.start
%p
  %b Stop:
  = @study_reservation.stop
%p
  %b Date:
  = @study_reservation.date
%p
  %b Name:
  = @study_reservation.name
%p
  %b
  = link_to 'Back', study_reservations_path
- if admin_signed_in?
  = link_to 'Edit', edit_study_reservation_path(@study_reservation)
  \|
  = link_to 'Back', study_reservations_path