config/routes.rb
Rails.application.routes.draw do

	resources :happenings

	resources :study_reservations
	
	get '/contracts/success'
	get '/contracts/failure'
	get '/amenities', to: 'static#amenities', as: :amenities
	get '/contracts_pricing', to: 'static#contracts_pricing', as: :pricing
	get '/galleries', to: 'static#galleries', as: :gallery
	get '/apartments', to: 'static#apartments', as: :apartments
	get '/tenant', to: 'static#tenant', as: :tenant
	get 'maintenances/created', to: 'maintenances#created'
	get '/buildings/:building_id/apartments/:semester_id', to: 'ajax#beds'
	get '/renew', to: 'contracts#renew'
	get '/userPayment', to: 'contracts#userPayment'
	get '/makePayment', to: 'static#makePayment'
	devise_for :admins
	root 'landing#landing'
	get '/contact', to: 'static#contact_manager', as: :contact_manager
	post '/contact', to: 'static#manager_email', as: :contact_email
	get '/choose/:semester_id/:building_id', to: 'static#choose'
	get '/choose/:semester_id', to: 'static#choose', as: :choose_apartment
	get '/complex', to: 'static#complex', as: :complex

	get '/success', to: 'contracts#success', as: :success

	post '/invoice', to: 'contracts#discounts', as: :discounts
	get '/invoice', to: 'contracts#discounts'

	get '/contracts/new/:building_id/:semester_id', to: 'contracts#new', as: :new_contract
	post '/contracts/new/:building_id/:semester_id', to: 'contracts#new'
	get '/buildings/:id/availability/:semester_id', to: 'availability#available'

	scope :admin do
		resources :amenities
		resources :galleries
		resources :buildings
		resources :semesters
		resources :contract_texts
		resources :maintenances
		resources :study_rooms
		resources :apartments

		
		get '/contracts', to: 'contracts#index', as: :contracts
		post '/contracts', to: 'contracts#create'
		get '/contracts/:id', to: 'contracts#show', as: :contract
		put '/contracts/:id', to: 'contracts#update'
		get '/contracts/:id/edit', to: 'contracts#edit', as: :edit_contract
		delete '/contracts/:id', to: 'contracts#destroy', as: :destroy_contract

		get '/', to: 'static#dashboard', as: :dashboard
		get '/marketing-text', to: 'static#marketing_text', as: :edit_text
		post '/marketing-text', to: 'static#edit_text', as: :update_text
	end

end

app/models/apartment.rb
# == Schema Information
#
# Table name: apartments
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  description :text
#  image_id    :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  building_id :integer
#

class Apartment < ActiveRecord::Base
	belongs_to :building
	has_many :beds

	validates :image_id, presence: true
	validates :title, presence: true, uniqueness: {scope: :building, message: 'An apartment with that number already exists in that building'}
	validates :description, presence: true

	before_destroy :backupItem
	after_destroy :deleteItem

	validates_presence_of :building

	# saves the item id before destroying
	def backupItem
		if self.image_id
			@public_id = self.image_id.split('/').last
			@public_id = @public_id.split('#').first
			@public_id = @public_id.split('.').first
		end
	end

	# after destroying the image from the db this will remove it from cloudinary
	def deleteItem
		if @public_id
			Cloudinary::Uploader.destroy(@public_id)
		end
	end
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_apartment, only: [:show, :edit, :update, :destroy]

  # GET /apartments
  # GET /apartments.json
  def index
    @apartments = Apartment.all
  end

  # GET /apartments/1
  # GET /apartments/1.json
  def show
  end

  # GET /apartments/new
  def new
    @apartment = Apartment.new
  end

  # GET /apartments/1/edit
  def edit
  end

  def create
    @apartment = Apartment.new(apartment_params)
    
    if params[:image_id].present?
      preloaded = Cloudinary::PreloadedFile.new(params[:image_id])         
      raise "Invalid upload signature" if !preloaded.valid
      @amenity.image_id = preloaded.identifier
    end

    respond_to do |format|
      if @apartment.save
        format.html { redirect_to @apartment, notice: 'Apartment was successfully created.' }
        format.json { render :show, status: :created, location: @apartment }
      else
        format.html { render :new }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartments/1
  # PATCH/PUT /apartments/1.json
  def update
    respond_to do |format|
      if @apartment.update(apartment_params)
        format.html { redirect_to @apartment, notice: 'Apartment was successfully updated.' }
        format.json { render :show, status: :ok, location: @apartment }
      else
        format.html { render :edit }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartments/1
  # DELETE /apartments/1.json
  def destroy
    @apartment.destroy
    respond_to do |format|
      format.html { redirect_to apartments_url, notice: 'Apartment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end




  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartment
      @apartment = Apartment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apartment_params
      params.require(:apartment).permit(:title, :description, :image_id)
    end
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/views/apartments/_form.html.haml
= form_for @apartment do |f|
	- if @apartment.errors.any?
		#error_explanation
			%h2= "#{pluralize(@apartment.errors.count, "error")} prohibited this apartment from being saved:"
			%ul
				- @apartment.errors.full_messages.each do |msg|
					%li= msg

	.row
		= label_tag :image, 'Image'
		= cl_image_upload_tag('apartment[image_id]', crop: :limit, width: 600, height: 400, id: :uploader)
		.progress-container
			.progress
				.progress-bar#progress-bar{role: :'progressbar', style: 'width: 0%;'}
		.preview
	.row
		= f.label :title
		= f.text_field :title
	.row
		= f.label :description
		= f.text_area :description
	.actions
		= f.submit 'Save'

app/views/apartments/edit.html.haml
%h1 Editing apartment

= render 'form'

= link_to 'Show', @apartment
\|
= link_to 'Back', apartments_path

app/views/apartments/index.html.haml
%h1 Listing apartments

%table
  %tr
    %th Title
    %th Description
    %th Image
    %th
    %th
    %th

  - @apartments.each do |apartment|
    %tr
      %td= apartment.title
      %td= apartment.description
      %td= apartment.image_id
      %td= link_to 'Show', apartment
      %td= link_to 'Edit', edit_apartment_path(apartment)
      %td= link_to 'Destroy', apartment, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Apartment', new_apartment_path

app/views/apartments/new.html.haml
%h1 New apartment

= render 'form'

= link_to 'Back', apartments_path

app/views/apartments/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @apartment.title
%p
  %b Description:
  = @apartment.description
%p
  %b Image:
  = @apartment.image_id

= link_to 'Edit', edit_apartment_path(@apartment)
\|
= link_to 'Back', apartments_path